version: '3'

vars:
  NODEJS_PROJECT: "github.com/pulumi/pulumi/sdk/v3/nodejs/cmd/pulumi-language-nodejs"
  NODEJS_VERSION:
    sh: cd ../../ && pulumictl get version --language javascript && cd sdk/nodejs

tasks:
  ensure:
    cmds:
      - yarn install
    status:
      - yarn install --check-files

  lint:
    cmds:
      - ./node_modules/.bin/tslint -c tslint.json -p tsconfig.json

  build:
    cmds:
      - go build -o ../../bin/pulumi-language-nodejs -ldflags "-X github.com/pulumi/pulumi/sdk/v3/go/common/version.Version={{.NODEJS_VERSION}}" {{.NODEJS_PROJECT}}
    sources:
      - ./cmd/pulumi-language-nodejs/*.go
    generates:
      - ../../bin/pulumi-language-nodejs
    method: checksum

#  build-package:
#    cmds:
#      - ./node_modules/.bin/tsc
#      - cp tests/runtime/jsClosureCases_8.js bin/tests/runtime
#      - cp tests/runtime/jsClosureCases_10_4.js bin/tests/runtime
#      - cp -R tests/automation/data/. bin/tests/automation/data/
#      - p README.md ../../LICENSE package.json ./dist/* bin/
#      - node ../../scripts/reversion.js bin/package.json {{.VERSION}}
#      - node ../../scripts/reversion.js bin/version.js {{.VERSION}}
#      - cp -R proto/. bin/proto/
#      - mkdir -p bin/tests/runtime/langhost/cases/
#      - find tests/runtime/langhost/cases/* -type d -exec cp -R {} bin/tests/runtime/langhost/cases/ \;
#
#  build:
#    cmds:
#      - task: build-package
#      - task: build-binary